// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLNhanVien.Context;

#nullable disable

namespace QLNhanVien.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QLNhanVien.Data.KinhNghiemLamViec", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("CongNghe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKinhNghiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ThoiGian")
                        .HasColumnType("float");

                    b.Property<string>("ViTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("IDNhanVien");

                    b.ToTable("KinhNghiemLamViecs");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CongNghe = "C#",
                            IDNhanVien = 1,
                            Mota = "Dự án phát triển phần mềm",
                            TenKinhNghiem = "Dự án A",
                            ThoiGian = 12.0,
                            ViTri = "Lập trình viên"
                        },
                        new
                        {
                            ID = 2,
                            CongNghe = "ASP.NET",
                            IDNhanVien = 1,
                            Mota = "Dự án thiết kế web",
                            TenKinhNghiem = "Dự án B",
                            ThoiGian = 8.0,
                            ViTri = "Thiết kế web"
                        },
                        new
                        {
                            ID = 3,
                            CongNghe = "Linux",
                            IDNhanVien = 3,
                            Mota = "Quản lý hệ thống mạng",
                            TenKinhNghiem = "Dự án C",
                            ThoiGian = 24.0,
                            ViTri = "Quản trị hệ thống"
                        });
                });

            modelBuilder.Entity("QLNhanVien.Data.KyNang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("KyNangs");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Mota = "Kỹ năng lập trình với C#",
                            Ten = "Lập trình C#"
                        },
                        new
                        {
                            ID = 2,
                            Mota = "Kỹ năng phát triển ứng dụng web với ASP.NET",
                            Ten = "Lập trình ASP.NET"
                        },
                        new
                        {
                            ID = 3,
                            Mota = "Kỹ năng làm việc với Entity Framework để truy cập dữ liệu",
                            Ten = "Entity Framework"
                        });
                });

            modelBuilder.Entity("QLNhanVien.Data.KyNang_NhanVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("IDKyNang")
                        .HasColumnType("int");

                    b.Property<int>("IDNhanVien")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IDKyNang");

                    b.HasIndex("IDNhanVien");

                    b.ToTable("KyNang_NhanViens");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            IDKyNang = 1,
                            IDNhanVien = 1
                        },
                        new
                        {
                            ID = 2,
                            IDKyNang = 3,
                            IDNhanVien = 1
                        },
                        new
                        {
                            ID = 3,
                            IDKyNang = 2,
                            IDNhanVien = 2
                        },
                        new
                        {
                            ID = 4,
                            IDKyNang = 3,
                            IDNhanVien = 3
                        });
                });

            modelBuilder.Entity("QLNhanVien.Data.NhanVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgheNghiep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("NhanViens");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            GioiTinh = "Nam",
                            NgheNghiep = "Lập trình viên",
                            Ten = "Nguyen Van A"
                        },
                        new
                        {
                            ID = 2,
                            GioiTinh = "Nữ",
                            NgheNghiep = "Thiết kế web",
                            Ten = "Tran Thi B"
                        },
                        new
                        {
                            ID = 3,
                            GioiTinh = "Nam",
                            NgheNghiep = "Quản trị hệ thống",
                            Ten = "Le Van C"
                        });
                });

            modelBuilder.Entity("QLNhanVien.Data.KinhNghiemLamViec", b =>
                {
                    b.HasOne("QLNhanVien.Data.NhanVien", "NhanVien")
                        .WithMany("KinhNghiemLamViecs")
                        .HasForeignKey("IDNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLNhanVien.Data.KyNang_NhanVien", b =>
                {
                    b.HasOne("QLNhanVien.Data.KyNang", "KyNang")
                        .WithMany("KyNang_NhanViens")
                        .HasForeignKey("IDKyNang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLNhanVien.Data.NhanVien", "NhanVien")
                        .WithMany("KyNang_NhanViens")
                        .HasForeignKey("IDNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KyNang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QLNhanVien.Data.KyNang", b =>
                {
                    b.Navigation("KyNang_NhanViens");
                });

            modelBuilder.Entity("QLNhanVien.Data.NhanVien", b =>
                {
                    b.Navigation("KinhNghiemLamViecs");

                    b.Navigation("KyNang_NhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
